---
- name: Apply roles to hosts
  hosts: all
  become: yes
  become_user: root
  remote_user: anupkumar
  become_method: su
  gather_facts: no
  no_log: false
  roles:
    - role: robin-ha-install
      tags:
        - ha-install
      any_errors_fatal: true

    - role: robin-non-ha-install
      tags:
        - non-ha-install
      any_errors_fatal: true  

    - role: robin-upgrade
      tags:
        - upgrade
      any_errors_fatal: true  

    - role: robin-uninstall
      tags:
        - uninstall
      any_errors_fatal: true  

    - role: artifactory-download
      tags:
        - download-robin-bin
      any_errors_fatal: true 

    - role: robin-precheck
      tags:
        - upgrade-precheck
      ignore_errors: yes  

    - role: cluster-state
      tags:
        - cluster-status