- name: Apply roles to hosts
  hosts: [primary-master]
  become: yes
  become_user: root
  remote_user: anupkumar
  become_method: su
  gather_facts: no
  no_log: false
  tasks
    - name: Include common tasks to find the active node
      include_tasks: roles/robin-upgrade/tasks/find-active-node.yaml
      name: "k8s plus upgrade - active"
      tags:
        - v5.4hf5