# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
if test -f "/root/bin/robinrc" ; then
    source /root/bin/robinrc
fi
export PATH=$PATH:/root/bin
