- name: Fetch IP from /etc/kubernetes/kubelet.conf
  shell: cat /etc/kubernetes/kubelet.conf |grep server |awk -F':' '{print $3}'| cut -d'/' -f3
  register: ip

- name: Fetch port from /etc/kubernetes/kubelet.conf
  shell: cat /etc/kubernetes/kubelet.conf |grep server |awk -F':' '{print $4}'
  register: port

- name: Fetch hostname IP 
  shell: hostname -i
  register: hostname_ip


- name: verify if ip from kubelet.conf matches hostname ip
  assert:
    that: ip.stdout == hostname_ip.stdout
    fail_msg: "replace hostname_ip in server: https://<hostname_ip>:36443 inside /etc/kubernetes/kubelet.conf before proceeding"
    success_msg: "passed"

- name: verify if port from kubelet.conf is 6443
  assert:
    that: port.stdout == '6443'
    fail_msg: "replace port 36443 with 6443 in server: https://<hostname_ip>:<port> inside /etc/kubernetes/kubelet.conf before proceeding"
    success_msg: "passed"    