---
# tasks file for robin-pre-check

- name: Import file system check
  import_tasks: filesystem-check.yaml
  tags: pre-check

- name: Import nodes status check
  import_tasks: node-status-check.yaml
  tags: pre-check

- name: Import Defunct/zombie process check on all nodes
  import_tasks: process-check.yaml
  tags: pre-check

- name: Import service status check
  import_tasks: service-status-check.yaml
  tags: pre-check

- name: Import k8s and robin pod status check
  import_tasks: pod-status-check.yaml
  tags: pre-check
  when: inventory_hostname in groups['primary-master']

- name: Import active robin jobs check
  import_tasks: robin-jobs-check.yaml
  tags: pre-check
  when: inventory_hostname in groups['primary-master']

- name: Import rpc-gssd service check on all nodes
  import_tasks: rpc-gssd-check.yaml
  tags: pre-check
  when: inventory_hostname in groups['primary-master']

- name: Import disk status check
  import_tasks: disk-status-check.yaml
  tags: pre-check

- name: Import volume status check
  import_tasks: vol-status-check.yaml
  tags: pre-check

- name: Import CPU Check
  import_tasks: cpu-status-check.yaml
  tags: pre-check
  when: inventory_hostname in groups['primary-master'] 

- name: Import cluster hostnames check
  import_tasks: verify-cluster-hostnames.yaml
  tags: pre-check
  when: inventory_hostname in groups['primary-master']     

- name: Import extra checks
  import_tasks: extra-checks.yaml
  tags: pre-check

- name: Import kubelet checks
  import_tasks: verify-kubelet-version.yaml
  tags: pre-check
  when: current_robin_version == '5.4.3-564'

- name: Import robin db checks
  import_tasks: robin-db-ldap-check.yaml
  tags: pre-check
  when: inventory_hostname in groups['primary-master'] and current_robin_version == '5.4.3-564'

- name: Import robin config check
  import_tasks: robin-config-suicide-check.yaml
  tags: pre-check
  when: inventory_hostname in groups['primary-master'] and current_robin_version == '5.4.3-564'

- name: Import robin nfs monitor schedule check
  import_tasks: robin-nfs-schedule-check.yaml
  tags: pre-check
  when: inventory_hostname in groups['primary-master'] and current_robin_version == '5.4.3-564'

- name: Import kubelet.conf check for IP
  import_tasks: kubelet-ip-check.yaml
  tags: pre-check
  when: inventory_hostname in groups['master'] and current_robin_version == '5.4.3-564'

- name: Import hungmounts check 
  import_tasks: hungmountscheck.yaml
  tags: pre-check

- name: Import auto rebalance check 
  import_tasks: auto-disk-rebalance-check.yaml
  tags: pre-check
  when: inventory_hostname in groups['primary-master']

- name: Import auto pilot check 
  import_tasks: autopilot-check.yaml
  tags: pre-check
  when: inventory_hostname in groups['primary-master']