---
# tasks file for robin-precheck

- name: Import file system check
  import_tasks: filesystem-check.yaml
  tags: precheck

- name: Import nodes status check
  import_tasks: node-status-check.yaml
  tags: precheck

- name: Import Defunct/zombie process check on all nodes
  import_tasks: process-check.yaml
  tags: precheck

- name: Import service status check
  import_tasks: service-status-check.yaml
  tags: precheck

- name: Import k8s and robin pod status check
  import_tasks: pod-status-check.yaml
  tags: precheck
  when: inventory_hostname in groups['primary-master']

- name: Import active robin jobs check
  import_tasks: robin-jobs-check.yaml
  tags: precheck
  when: inventory_hostname in groups['primary-master']

- name: Import rpc-gssd service check on all nodes
  import_tasks: rpc-gssd-check.yaml
  tags: precheck
  when: inventory_hostname in groups['primary-master']

- name: Import disk status check
  import_tasks: disk-status-check.yaml
  tags: precheck

- name: Import volume status check
  import_tasks: vol-status-check.yaml
  tags: precheck

- name: Import CPU Check
  import_tasks: cpu-status-check.yaml
  tags: precheck
  when: inventory_hostname in groups['primary-master'] 

- name: Import cluster hostnames check
  import_tasks: verify-cluster-hostnames.yaml
  tags: precheck
  when: inventory_hostname in groups['primary-master']     