- name: Host upgrade
  shell: cd /root/build/{{ robin_version }} && ./host-script-{{ os_version }}-{{ robin_version }}.sh upgrade --host-type=physical --yes --force --silent --ip-protocol={{ ip_protocol }}
  args:
    executable: /bin/bash
  async: 3600
  poll: 60