- name: Host upgarde
  shell: cd /root/build/{{ robin_version }} && ./host-script-{{ os_version }}-{{ robin_version }}.sh upgrade --host-type=physical --yes --force --silent --ip-protocol=ipv4 
  #shell: cd /root/build/{{ robin_version }} && ./host-script-el7-{{ robin_version }}.sh upgrade --host-type=physical --yes --force --silent --ip-protocol=ipv6
  async: 3600
  poll: 60
  tags: [v5.4]