- name: K8s Upgrade on master 1
  shell: cd /root/build/{{ robin_version }} && ./k8s-script-el8-{{ robin_version }}.sh upgrade --kubeconfig=/tmp/kube.config --primary-cp-node  --host-type=physical --yes --force --silent --ip-protocol=ipv4
  async: 3600
  poll: 60
  when: inventory_hostname in groups['primary-master']
  tags: [v5.4]

- name: K8s Upgrade on  secondary masters
  shell: cd /root/build/{{ robin_version }} && ./k8s-script-el8-{{ robin_version }}.sh upgrade --kubeconfig=/tmp/kube.config --host-type=physical --yes --force --silent --ip-protocol=ipv4
  async: 3600
  poll: 60
  when: inventory_hostname in groups['secondary-master']
  tags: [v5.4]

#- name: K8s Upgrade on  master 3
#  shell: cd /root/build/{{ robin_version }} && ./k8s-script-el8-{{ robin_version }}.sh upgrade --kubeconfig=/tmp/kube.config --host-type=physical --yes --force --silent --ip-protocol=ipv4
#  async: 3600
#  poll: 60
#  when: inventory_hostname in groups['secondary-master'][1]
#  tags: [v5.4]

- name: K8s Upgrade on worker nodes
  shell: cd /root/build/{{ robin_version }} && ./k8s-script-el8-{{ robin_version }}.sh upgrade --kubeconfig=/tmp/kube.config --host-type=physical --yes --force --silent --ip-protocol=ipv4
  async: 3600
  poll: 60
  when: inventory_hostname not in groups['primary-master'] and inventory_hostname not in groups['secondary-master']
  tags: [v5.4]

