- name: Fetch kubeconfig from primary-master
  fetch:
    src: /etc/kubernetes/admin.conf # Source file path on primary-master[0]
    dest: /tmp/  # Destination directory on the Ansible control machine
    flat: yes
  delegate_to: "{{ groups['primary-master'][0] }}"
  run_once: yes  # Run this task only once on primary-master[0]
  tags: v5.4

- name: Copy the kubeconfig to all hosts
  copy:
    src: "/tmp/admin.conf"  # Source file path on the Ansible control machine
    dest: /tmp/kube.config   # Destination path on other nodes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all'] }}"
  tags: v5.4

- name: K8s Pre upgrade
  shell: cd /root/build/{{ robin_version }} && ./k8s-script-el8-{{ robin_version }}.sh pre-upgrade --kubeconfig=/tmp/kube.config --host-type=physical --yes --force --silent --ip-protocol=ipv4
  #shell: cd /root/build/{{ robin_version }} && ./k8s-script-el7-{{ robin_version }}.sh pre-upgrade --kubeconfig=/tmp/kube.config --host-type=physical --yes --force --silent --ip-protocol=ipv6
  async: 3600
  poll: 60
  tags: v5.4

- name: K8splus Pre upgrade
  shell: cd /root/build/{{ robin_version }} && ./k8splus-script-{{ robin_version }}.sh pre-upgrade --host-type=physical --silent --ip-protocol=ipv4
  #shell: cd /root/build/{{ robin_version }} && ./k8splus-script-{{ robin_version }}.sh pre-upgrade --host-type=physical --silent --ip-protocol=ipv6
  async: 3600
  poll: 60
  when: inventory_hostname in groups['primary-master'][0]
  tags: v5.4