- name: K8s plus Upgrade on master
  shell: cd /root/build/{{ robin_version }} && ./k8splus-script-{{ robin_version }}.sh upgrade --host-type=physical --silent --ip-protocol=ipv4 --ignore-warnings
  #shell: cd /root/build/{{ robin_version }} && ./k8splus-script-{{ robin_version }}.sh upgrade --host-type=physical --silent --ip-protocol=ipv6
  async: 3600
  poll: 60
  when: inventory_hostname in groups['primary-master'][0]
  tags: [v5.4]