- name: Robin upgrade
  shell: cd /root/build/{{ robin_version }} && ./robin-script-{{ robin_version }}.sh upgrade --kubeconfig=/tmp/kube.config --yes --force --username={{ robin_user }} --password={{ robin_pass }} --silent --ip-protocol={{ ip_protocol }}
  async: 3600
  poll: 60
  when: inventory_hostname in groups['primary-master'][0] and upgrade_release_major_version == '5.4.3' 
  tags:
    - v5.4hf3

- name: Robin upgrade
  shell: cd /root/build/{{ robin_version }} && ./robin-script-{{ robin_version }}.sh upgrade --kubeconfig=/tmp/kube.config --yes --force --username={{ robin_user }} --password={{ robin_pass }} --silent 
  async: 3600
  poll: 60
  when: inventory_hostname in groups['primary-master'][0] and upgrade_release_major_version == '5.5.0' 
  tags:
    - v5.4hf3

- name: Include common tasks to find the active node
  include_tasks: find-active-node.yaml
  name: "Robin upgrade - active"
  tags:
    - v5.4hf5


- name: Robin upgrade on Active Master
  shell: cd /root/build/{{ robin_version }} && ./robin-script-{{ robin_version }}.sh upgrade --kubeconfig=/tmp/kube.config --yes --force --username={{ robin_user }} --password={{ robin_pass }} --silent --ip-protocol={{ ip_protocol }}
  async: 3600
  poll: 60
  when: ansible_facts['fqdn'] == active_node.results[0].stdout and upgrade_release_major_version == '5.4.3'
  tags:
    - v5.4hf5

- name: Robin upgrade on Active Master
  shell: cd /root/build/{{ robin_version }} && ./robin-script-{{ robin_version }}.sh upgrade --kubeconfig=/tmp/kube.config --yes --force --username={{ robin_user }} --password={{ robin_pass }} --silent 
  async: 3600
  poll: 60
  when: ansible_facts['fqdn'] == active_node.results[0].stdout and upgrade_release_major_version == '5.5.0'
  tags:
    - v5.4hf5

#- name: Robin upgrade for 5.3
#  tags: [v5.3]
#  block:
#    - name: Check if kms=vault is present
#      command: grep -q "kms=vault" /etc/robin/bootstrap/bootstrap_details
#      register: grep_result
#      ignore_errors: yes
#      when: inventory_hostname in groups['primary-master'][0]
#
#    - name: Upgrade Robin on kms=vault
#      shell: cd /root/build/{{ robin_version }} && ./{{ script_name }} upgrade-robin  --username={{ robin_user }} --password={{ robin_pass }} --vault-addr=https://psvau-service.1u1.local:8200
#      async: 3600
#      poll: 60
#      when: grep_result.rc == 0 and inventory_hostname in groups['primary-master'][0]
#
#    - name: Upgrade Robin on kms=k8s
#      shell: cd /root/build/{{ robin_version }} && ./{{ script_name }} upgrade-robin  --username={{ robin_user }} --password={{ robin_pass }}
#      async: 3600
#      poll: 60
#      when: grep_result.rc != 0 and inventory_hostname in groups['primary-master'][0]
