- name: Robin Pre upgrade
  shell: cd /root/build/{{ robin_version }} && ./robin-script-{{ robin_version }}.sh pre-upgrade --yes --force --username={{ robin_user }} --password={{ robin_pass }} --silent --ip-protocol=ipv4
  async: 3600
  poll: 60
  when: inventory_hostname in groups['primary-master'][0]
  tags: [v5.4]

#- name: Pre Robin upgrade 1
#  shell: cd /root/build/{{ robin_version }} && ./{{ script_name }} pre-robin-upgrade  --username={{ robin_user }} --password={{ robin_pass }}
#  async: 3600
#  poll: 60
#  when: inventory_hostname in groups['primary-master'][0]
#  tags: [v5.3]
#
#- name: Pre Robin upgrade 2
#  shell: cd /root/build/{{ robin_version }} && ./{{ script_name }} pre-robin-upgrade-all-hosts  --username={{ robin_user }} --password={{ robin_pass }}
#  tags: [v5.3]