- name: Robin upgrade
  shell: |
    source /root/.bashrc 
    cd /root/build/{{ robin_version }}
    ./robin-script-{{ robin_version }}.sh upgrade --kubeconfig=/root/kube.config --yes --force --username={{ robin_user }} --password={{ robin_pass }} --silent --ip-protocol={{ ip_protocol }}
  args:
    executable: /bin/bash
  async: 3600
  poll: 60
  when: inventory_hostname in groups['primary-master'][0] and upgrade_release_major_version == '5.4.3' 
  tags:
    - v5.4hf3

- name: Robin upgrade
  shell: |
    source /root/.bashrc
    cd /root/build/{{ robin_version }}
    ./robin-script-{{ robin_version }}.sh upgrade --kubeconfig=/root/kube.config --yes --force --username={{ robin_user }} --password={{ robin_pass }} --silent 
  args:
    executable: /bin/bash
  async: 3600
  poll: 60
  when: inventory_hostname in groups['primary-master'][0] and upgrade_release_major_version == '5.5.0' 
  tags:
    - v5.4hf3

- name: Include common tasks to find the active node
  include_tasks: find-active-node.yaml
  name: "Robin upgrade - active"
  tags:
    - v5.4hf5

