# - name: Import host upgrade
#   import_tasks: host-upgrade.yaml


# - name: Import k8s upgrade
#   import_tasks: k8s-upgrade.yaml


# # Set k8s_versions based on robin versions
# - set_fact:
#     k8s_versions: "{{ v53_to_vhf3_chain_upgrade_k8s_versions }}"
#   when: current_robin_version == '5.3.13'
#   tags: 
#     - v5.3

# # Set k8s_versions based on robin versions
# - set_fact:
#     k8s_versions: "{{ v543hf3_to_vhf5_chain_upgrade_k8s_versions }}"
#   when: current_robin_version == '5.4.3-355'
#   tags: 
#     - v5.4.3hf3

# # Set k8s_versions based on robin versions
# - set_fact:
#     k8s_versions: "{{ v543hf5_to_v550_chain_upgrade_k8s_versions }}"
#   when: current_robin_version == '5.4.3-564'
#   tags: 
#     - v5.4.3hf5


# - name: Include k8s chain upgrade
#   include_tasks: k8s-chain-upgrade.yaml
#   loop: "{{ k8s_versions }}"
#   loop_control:
#     loop_var: k8s_version
  

# - name: Import k8s plus upgrade
#   import_tasks: k8s-plus-upgrade.yaml


- name: Import robin upgrade
  import_tasks: robin-upgrade.yaml