- name: Import host upgrade
  import_tasks: host-upgrade.yaml

- name: capture cluster state before k8s upgrade
  import_role:
    name: cluster-state
  vars:
    result_path: /root/build/{{ robin_version }}/k8s-upgrade
    cluster_state: "full"
  tags:
    - always

- name: Import k8s upgrade
  import_tasks: k8s-upgrade.yaml


# - name: capture cluster state before k8s-chain upgrade
#   import_role:
#     name: cluster-state
#   vars:
#     result_path: /root/build/{{ robin_version }}/k8s-chain-upgrade
#     cluster_state: "full"
#   tags:
#     - always


#- name: Set k8s_versions based on robin versions
- set_fact:
    k8s_versions: "{{ v53_to_vhf3_chain_upgrade_k8s_versions }}"
  when: current_robin_version == '5.3.13'
  tags: 
    - v5.3

#- name: Set k8s_versions based on robin versions
- set_fact:
    k8s_versions: "{{ v543hf3_to_vhf5_chain_upgrade_k8s_versions }}"
  when: current_robin_version == '5.4.3-355'
  tags: 
    - v5.4.3hf3

#- name: Set k8s_versions based on robin versions
- set_fact:
    k8s_versions: "{{ v543hf5_to_v550_chain_upgrade_k8s_versions }}"
  when: current_robin_version == '5.4.3-564'
  tags: 
    - v5.4.3hf5

#- set_fact:
#    k8s_versions:
#      - 1.22.5
#      - 1.23.8
#      - 1.24.8
#      - 1.25.7
#  tags: [v5.4]


- name: Include k8s chain upgrade
  include_tasks: k8s-chain-upgrade.yaml
  loop: "{{ k8s_versions }}"
  loop_control:
    loop_var: k8s_version
  

- name: Import k8s plus upgrade
  import_tasks: k8s-plus-upgrade.yaml


# - name: capture cluster state before robin upgrade
#   import_role:
#     name: cluster-state
#   vars:
#     result_path: /root/build/{{ robin_version }}/robin-upgrade
#     cluster_state: "full"
#   tags:
#     - always

- name: Import robin upgrade
  import_tasks: robin-upgrade.yaml