---
# tasks file for robin-non-ha-install
#- name: Import Artifacts Download
#  import_tasks: artifacts-download.yaml
#  tags:
#    - image-download
#    - image-load

- name: Import bashrc file
  import_tasks: update-bashrc.yaml
  tags:
    - always

- name: Import install script
  import_tasks: robin-install.yaml
  tags:
    - v5.4

# - name: Import robin license activation
#   import_tasks: license-activate.yaml
#   tags:
#     - activate_license
#   when: inventory_hostname in groups['primary-master']  