- name: Uninstall hosts configuration from all nodes
  shell: cd /root/build/{{ robin_version }} && ./host-script-{{ os_version }}-{{ robin_version }}.sh uninstall -y --force
  register: host_uninstall_ouptput
  async: 3600
  poll: 60
  tags:
    - v5.4

- name: Display host uninstall output
  debug:
    var: host_uninstall_ouptput.stdout    