- name: Uninstall k8 configuration from all worker nodes
  shell: cd /root/build/{{ robin_version }} && ./k8s-script-{{ os_version }}-{{ robin_version }}.sh  cleanup -y --force
  register: k8s_uninstall_worker_output
  async: 3600
  poll: 60
  when: inventory_hostname in groups['worker']
  tags:
    - v5.4

- name: Display k8s uninstall worker output
  debug:
    var: k8s_uninstall_worker_output.stdout
  when: inventory_hostname in groups['worker']


- name: Uninstall k8 configuration from secondary master nodes
  shell: cd /root/build/{{ robin_version }} && ./k8s-script-{{ os_version }}-{{ robin_version }}.sh  cleanup -y --force
  register: k8s_uninstall_sec_master_output
  async: 3600
  poll: 60
  when: inventory_hostname in groups['secondary-master']
  tags:
    - v5.4

- name: Display k8s uninstall secondary master output
  debug:
    var: k8s_uninstall_sec_master_output.stdout
  when: inventory_hostname in groups['secondary-master']


- name: Uninstall k8 configuration from primary master nodes
  shell: cd /root/build/{{ robin_version }} && ./k8s-script-{{ os_version }}-{{ robin_version }}.sh  cleanup -y --force
  register: k8s_uninstall_master_output
  async: 3600
  poll: 60
  when: inventory_hostname in groups['primary-master']
  tags:
    - v5.4

- name: Display k8s uninstall primary master output
  debug:
    var: k8s_uninstall_master_output.stdout
  when: inventory_hostname in groups['primary-master'] 