---
# tasks file for robin-uninstall-component
- name: Import app clean up
  import_tasks: robin-app-cleanup.yml
  when: inventory_hostname in groups['primary-master']
  ignore_errors: yes
  tags:
    - v5.4
    - robin-app-cleanup

- name:  Import cnp uninstall
  import_tasks: robin-cnp-uninstall.yml
  # ignore_errors: yes
  tags:
    - v5.4
    - robin-cnp-uninstall
