- name: get app json file
  shell: source /root/.bash_profile && rm -rf app.json && robin login {{ robin_user }} --password {{ robin_pass }} && robin app list --json > /root/app.json
  args:
    executable: /bin/bash
  async: 60  # Maximum time in seconds the task is allowed to run
  poll: 0   

- name: Fetch app.json from remote host to local directory
  fetch:
    src: /root/app.json
    dest: "{{ playbook_dir }}/roles/robin-uninstall-component/files/app.json"
    flat: yes

- name: Load data from JSON file
  set_fact:
    app_data: "{{ lookup('file', 'app.json') | from_json }}"

- name: Delete all robin app
  shell: source /root/.bash_profile && robin login {{ robin_user }} --password {{ robin_pass }} && robin app delete {{ item.name }} --iter -y --force --wait
  args:
    executable: /bin/bash
  async: 60  # Maximum time in seconds the task is allowed to run
  poll: 0   
  loop: "{{ app_data.robin.apps }}"

- name: Delete app.json file
  file:
    path: "{{ playbook_dir }}/roles/robin-uninstall-component/files/app.json"
    state: absent